name: Java CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
    - name: Grant execute permission to Gradle wrapper
      run: chmod +x ./gradlew
    - name: Build
      run: ./gradlew assemble
    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build/libs/*-plain.jar

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
    - name: Grant execute permission to Gradle wrapper
      run: chmod +x ./gradlew
    - name: Run tests
      run: ./gradlew test
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: build/test-results/test/**/TEST-*.xml

  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
    - name: Grant execute permission to Gradle wrapper
      run: chmod +x ./gradlew
    - name: Prepare for publish
      run: |
        echo "Preparing for publish"
        ./gradlew assemble
